services:
  qhana-plugin-runner:
    image: ${PLUGIN_RUNNER_IMAGE}
    depends_on:
      - redis
      - postgres
      - minio
    ports:
      - "5005:8080"
    volumes:
      - instance:/app/instance
    environment:
      CONCURRENCY: 2
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      CELERY_QUEUE: "qhana_queue1"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres:5432/default_db"
      DEFAULT_FILE_STORE: "minio"
      MINIO_CLIENT: '{"endpoint": "localhost:9000", "access_key": "QHANA", "secret_key": "QHANAQHANA", "secure": false}'
      LOCALHOST_PROXY_PORTS: &localhost-proxy-ports ":5005 :5006 :5007 :9000 :9001 :9091 ${EXTRA_PROXY_PORTS}"
      GIT_PLUGINS: &git-plugins "git+https://github.com/UST-QuAntiL/qhana-plugin-runner.git@main#subdirectory=/stable_plugins\ngit+https://github.com/UST-QuAntiL/nisq-analyzer-prio-service.git@master#subdirectory=/plugins"
      PLUGIN_FOLDERS: &plugin-folders ./git-plugins/classical_ml/data_preparation:./git-plugins/classical_ml/scikit_ml:./git-plugins/demo:./git-plugins/infrastructure:./git-plugins/muse:./git-plugins/quantum_ml/pennylane_qiskit_ml
      NISQ_ANALYZER_UI_URL: http://localhost:5009
    extra_hosts:
      - "host.docker.internal:host-gateway"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: default_db
  postgres-registry:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: default_db
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: QHANA
      MINIO_ROOT_PASSWORD: QHANAQHANA
    ports:
      - "9000:9000"
      - "9001:9001"
  muse-db:
    image: ghcr.io/ust-quantil/mini-muse:main
  worker:
    image: ${PLUGIN_RUNNER_IMAGE}
    depends_on:
      - qhana-plugin-runner
    volumes:
      - instance:/app/instance
    environment:
      CONTAINER_MODE: worker
      CONCURRENCY: 2
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      CELERY_QUEUE: "qhana_queue1"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres:5432/default_db"
      DEFAULT_FILE_STORE: "minio"
      MINIO_CLIENT: '{"endpoint": "localhost:9000", "access_key": "QHANA", "secret_key": "QHANAQHANA", "secure": false}'
      LOCALHOST_PROXY_PORTS: *localhost-proxy-ports
      GIT_PLUGINS: *git-plugins
      PLUGIN_FOLDERS: *plugin-folders
    extra_hosts:
      - "host.docker.internal:host-gateway"
  backend:
    image: ${BACKEND_IMAGE}
    volumes:
      - experiments:/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      LOCALHOST_PROXY_PORTS: *localhost-proxy-ports
      QHANA_HOST: http://localhost:9091
    ports:
      - 9091:9090
  ui:
    image: ${UI_IMAGE}
    ports:
      - 8080:8080
    environment:
      PLUGIN_REGISTRY_PROTOCOL: "http:"
      PLUGIN_REGISTRY_HOSTNAME: localhost
      PLUGIN_REGISTRY_PORT: 5006
      PLUGIN_REGISTRY_PATH: /api/
    extra_hosts:
      - "host.docker.internal:host-gateway"
  registry:
    image: ${REGISTRY_IMAGE}
    ports:
      - "5006:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WAIT_HOSTS: redis:6379, postgres-registry:5432, qhana-plugin-runner:8080
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 600
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      CELERY_QUEUE: "registry_queue"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres-registry:5432/default_db"
      LOCALHOST_PROXY_PORTS: *localhost-proxy-ports
      INITIAL_PLUGIN_SEEDS: "http://localhost:5005"
      PRECONFIGURED_SERVICES: '[{"serviceId": "qhana-backend", "name": "Backend", "url": "http://localhost:9091"}]'
  registry-worker:
    image: ${REGISTRY_IMAGE}
    ports:
      - "5007:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WAIT_HOSTS: redis:6379, postgres-registry:5432, qhana-plugin-runner:8080
      WAIT_SLEEP_INTERVAL: 5
      WAIT_TIMEOUT: 600
      CONTAINER_MODE: worker
      BROKER_URL: redis://redis:6379
      RESULT_BACKEND: redis://redis:6379
      CELERY_QUEUE: "registry_queue"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:password@postgres-registry:5432/default_db"
      LOCALHOST_PROXY_PORTS: *localhost-proxy-ports
      PLUGIN_DISCOVERY_INTERVAL: 60
      PERIODIC_SCHEDULER: "true"
  chrome:
    image: ghcr.io/philwun/selenium-chrome-proxy:master
    ports:
      - "4444:4444"
      - "7900:7900"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      shm-size: "4g"
      LOCALHOST_PROXY_PORTS: ":8080 :5006 :9091 :5005"

volumes:
  minio:
  instance:
  experiments:
  exec_data:
